### PR TITLE
fix(network): correct msg processing

### LINKED ISSUE #36: Interop with go
Documenting things here.

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes #36

### CODE REVIEW

File: src/network/index.js [hunk 1]
```diff
@@ -47,14 +47,12 @@ module.exports = class Network {
   }
 
   _onConnection (conn) {
+    log('connected')
```
Comment (diasdavid) [inline src/network/index.js]: `s/connected/new bitswap connection`
